
version: {build}.0.0
configuration: Release

environment:
  apiKey:
    secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc

branches:
  except:
    - master

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: minimal

on_success:
  - ps: Write-Host $env:appveyor_build_version
  - ps: '& ".\NuGet\NuGet Package and Package.ps1" -Version $env:appveyor_build_version -NuGet "C:\Tools\NuGet\nuget.exe" -feedSource https://www.myget.org/F/openrealestate/api/v2 -apiKey $env:apiKey'

cache:
  - packages -> **\packages.config
